spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${APP_KEYCLOAK_URL:http://keycloak:8080/realms/prolance}
          jwk-set-uri: ${APP_KEYCLOAK_URL}/protocol/openid-connect/certs
          
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,beans,refresh,env,configprops
