spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL:http://keycloak:8080/realms/prolance}

services:
  tenant-service:
    url: http://localhost:8081/api/v1/
    base-url: http://localhost:8081/
  crm-service:
    url: http://localhost:8082/api/v1/
    base-url: http://localhost:8082/
  
eureka:
  instance:
    prefer-ip-address: true
