spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://api.dxcprolance.site/realms/prolance
          jwk-set-uri: http://keycloak.prolance.local:8080/realms/prolance/protocol/openid-connect/certs
