spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URL:http://keycloak:8080/realms/prolance}

services:
  tenant-service:
    url: http://tenant-service:8080/api/v1/
    base-url: http://tenant-service:8080/
  crm-service:
    url: http://crm-service:8080/api/v1/
    base-url: http://crm-service:8080/
  project-service:
    url: http://project-service:8080/api/v1/
    base-url: http://project-service:8080/
  
eureka:
  instance:
    prefer-ip-address: true
