
logging:
  level:
    com.dxc.tenantService: OFF
    root: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF